# 07 — NDMM PBMC Deep-Clean: Doublet Cluster Removal & Label Correction
### By [Mansi Singh](mansi.singh@alleninstitute.org), Comp Bio, Allen Institute for Immunology
**Aim:** Remove manually annotated doublet clusters from each L3 cell-type subset and apply label corrections (e.g., Core CD14 monocyte clusters 5/6/8 → Other_DC). Export cleaned per-cell-type objects and combined doublet metadata.

## 1 Setup

In [ ]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=RuntimeWarning)

import os
import re
import glob
from datetime import date

import numpy as np               # Numerical computation
import pandas as pd              # DataFrames
import scanpy as sc              # Single-cell analysis
import hisepy                    # HISE platform utilities

In [ ]:
# Output directory for deep-cleaned objects
out_dir = '../../../data/rna/ndmm-pbmc-celltypes-deepcleaned-objs/'
os.makedirs(out_dir, exist_ok=True)

### 1.1 Helper Functions

In [ ]:
def format_cell_type(cell_type):
    """Convert L3 label to file-safe format: '+' → 'pos', '-' → 'neg', ' ' → '_'."""
    cell_type = re.sub('\\+', 'pos', cell_type)
    cell_type = re.sub('-', 'neg', cell_type)
    cell_type = re.sub(' ', '_', cell_type)
    return cell_type

In [ ]:
def get_filepaths_with_glob(root_path: str, file_regex: str):
    """Return list of file paths matching a glob pattern in root_path."""
    return glob.glob(os.path.join(root_path, file_regex))

In [ ]:
# NOTE: Legacy HISE project store search — not needed for local workflow.
# search_id was used to locate files in the HISE project store.
# The cells below that reference h5ad_uuids / sort_adata_uuid
# are retained for provenance but the main workflow reads from local paths.

In [16]:
ps_df = hisepy.list_files_in_project_store('mildModLongi')
ps_df = ps_df[['id', 'name']]

In [17]:
search_df = ps_df[ps_df['name'].str.contains(search_id)]
search_df = search_df.sort_values('name')

In [18]:
h5ad_df = search_df[search_df['name'].str.contains('.h5ad')]

In [20]:
h5ad_uuids = {}
for i in range(h5ad_df.shape[0]):
    fn = h5ad_df['name'].tolist()[i]
    group_name = re.sub('.+pbmc_', '', fn)
    group_name = re.sub('_init.+', '', group_name)
    h5ad_uuids[group_name] = h5ad_df['id'].tolist()[i]

In [22]:
len(h5ad_uuids)

71

In [38]:
# run once
for uuid in h5ad_uuids.values():
    sort_adata_uuid(uuid, sort_cols = ['AIFI_L3'])

downloading fileID: 06e59640-de3c-45cf-b1bc-4150e29046d8
Files have been successfully downloaded!
downloading fileID: a9b29bba-ec08-456d-b83e-2d08726e6b28
Files have been successfully downloaded!
downloading fileID: c77cfb52-7342-4ab0-87f2-55ff0c1500c2
Files have been successfully downloaded!
downloading fileID: 09ee8060-91ed-4932-813e-723c801183ec
Files have been successfully downloaded!
downloading fileID: 2da73675-0401-4527-96b3-764fbcdfab45
Files have been successfully downloaded!
downloading fileID: 930e3900-7436-4bb9-9a16-257f73fef9d9
Files have been successfully downloaded!
downloading fileID: 3ce92a53-50ab-4fb1-84f5-87c3a7ce94a6
Files have been successfully downloaded!
downloading fileID: 58173c98-4b34-44c4-8887-7c18a985f49c
Files have been successfully downloaded!
downloading fileID: 832021ea-284a-4581-965c-56c21fb1610c
Files have been successfully downloaded!
downloading fileID: 68a3ee87-b387-4cde-8dff-f01715d98dfd
Files have been successfully downloaded!
downloading fileID: df75e402-701a-4cb2-b452-dcafebd9b17c
Files have been successfully downloaded!
downloading fileID: 0b29e0a8-0a29-409a-95f4-eee2698d5a8e
Files have been successfully downloaded!
downloading fileID: 4e1ab1c2-7799-414c-96d7-8b361554a263
Files have been successfully downloaded!
downloading fileID: 5e7d04d3-3e0c-4a3d-8cb5-7fc00048bcfd
Files have been successfully downloaded!
downloading fileID: 9561af1b-7d7d-4685-9d87-488ba17d5130
Files have been successfully downloaded!
downloading fileID: 61208bae-c7b4-4d76-a8b4-67bde16b680b
Files have been successfully downloaded!
downloading fileID: e0345a8e-0e11-4d16-9268-d75cb22e8b22
Files have been successfully downloaded!
downloading fileID: a5172eee-3af6-441f-9b68-b15e636f55a6
Files have been successfully downloaded!
downloading fileID: d07d92ca-1890-4636-a748-e18adb99d35b
Files have been successfully downloaded!
downloading fileID: 8118403d-56b8-435c-86fa-254c5549336b
Files have been successfully downloaded!
downloading fileID: 64768350-651a-4d1c-b419-f9305c77ca97
Files have been successfully downloaded!
downloading fileID: e875a9ca-5edb-49cf-9f9b-d86c86e13d1f
Files have been successfully downloaded!
downloading fileID: 066e40e5-9695-41e9-aa63-659a4a5022e8
Files have been successfully downloaded!
downloading fileID: 11573895-180b-4fc7-a3c6-9899b5036948
Files have been successfully downloaded!
downloading fileID: b8cff871-6715-46b4-ab95-a8f3c0a1213a
Files have been successfully downloaded!
downloading fileID: be73d36c-2784-4cc2-8b80-c1402bff332e
Files have been successfully downloaded!
downloading fileID: 5e474f8d-5fce-4413-8764-dc01ca24e006
Files have been successfully downloaded!
downloading fileID: 2fa20759-2b54-4b79-9ea8-53ea0021ca0c
Files have been successfully downloaded!
downloading fileID: 6b1f1649-5804-450d-9f8a-e39845bd3076
Files have been successfully downloaded!
downloading fileID: 091b65e9-9221-4de6-85f0-8c5b17a947ed
Files have been successfully downloaded!
downloading fileID: 356788d6-7416-4547-b782-af9fbc133bf8
Files have been successfully downloaded!
downloading fileID: b66e7cc0-9e90-489f-9f06-a703eb917532
Files have been successfully downloaded!
downloading fileID: 244daa73-f630-4e8b-bedc-897235d84dc9
Files have been successfully downloaded!
downloading fileID: 6ce8c9ff-73a8-4fa2-a23e-226b374e770d
Files have been successfully downloaded!
downloading fileID: 7aa8df74-1eee-4e1a-9df0-e54740312608
Files have been successfully downloaded!
downloading fileID: 37c34cd4-439b-4d6f-a6fb-d3baad27b80b
Files have been successfully downloaded!
downloading fileID: e71247f4-0e85-46a9-a690-7e91ba0eb729
Files have been successfully downloaded!
downloading fileID: 97f7cbbe-f5df-4c68-9da9-5ae9a08ecca0
Files have been successfully downloaded!
downloading fileID: f7c44814-e794-4dfe-a1ed-06f5353b8703
Files have been successfully downloaded!
downloading fileID: 29614055-a84f-4f9a-a24a-60a89cb8913a
Files have been successfully downloaded!
downloading fileID: da932479-af5c-42ab-8ae1-9a5ca77489a5
Files have been successfully downloaded!
downloading fileID: 17e213af-58e7-4c22-8747-042ac08144eb
Files have been successfully downloaded!
downloading fileID: 5ec22908-2142-40c3-b96b-b8e0b4ede049
Files have been successfully downloaded!
downloading fileID: 83d219fc-1413-4c75-8879-80c43fa5613d
Files have been successfully downloaded!
downloading fileID: 8270ac6d-ce24-4fe4-baa5-e8c75d29dd43
Files have been successfully downloaded!
downloading fileID: 77248296-0779-4065-aa86-22edc245893e
Files have been successfully downloaded!
downloading fileID: 570dbdb3-0816-4c7e-9d3c-44971859c99d
Files have been successfully downloaded!
downloading fileID: 78254ae0-1d3a-44d1-b5a4-1488900b02bc
Files have been successfully downloaded!
downloading fileID: 6af802a2-d8b1-4528-8d75-b0087dc3ddda
Files have been successfully downloaded!
downloading fileID: ffcc3c90-7adf-4038-aa26-22015703c223
Files have been successfully downloaded!
downloading fileID: b9a80b16-cfbc-448c-a427-1ac7f3b5417f
Files have been successfully downloaded!
downloading fileID: 86ded484-5ab9-4a36-905f-9b8e76c8f2d5
Files have been successfully downloaded!
downloading fileID: 5701e6da-8dd9-4966-8229-ac0cd293fb46
Files have been successfully downloaded!
downloading fileID: 6a98b56b-d102-422e-aad1-94fd65e09854
Files have been successfully downloaded!
downloading fileID: efdc5c9b-0d1d-4c75-bfd8-595d740e9085
Files have been successfully downloaded!
downloading fileID: 300db5bc-9c1b-4b33-a45f-57252520431c
Files have been successfully downloaded!
downloading fileID: 1c06a139-c0a0-4153-ab49-4a0a8032176d
Files have been successfully downloaded!
downloading fileID: 646e0537-de50-477d-839e-dafbbb9f8384
Files have been successfully downloaded!
downloading fileID: 028ce38f-5d8f-4692-93de-1515234c75b6
Files have been successfully downloaded!
downloading fileID: 4b65314c-b6a4-48a9-960a-1fa6fa24fa20
Files have been successfully downloaded!
downloading fileID: 95337b42-f7c2-4380-9f9e-68e5c9a618ac
Files have been successfully downloaded!
downloading fileID: 5f856069-4932-4e2f-8333-be3691c0ec1c
Files have been successfully downloaded!
downloading fileID: 07183e36-7cfd-49de-80d8-0a2e1d956d71
Files have been successfully downloaded!
downloading fileID: 36368d76-4020-40b5-9c8f-5595b52094f1
Files have been successfully downloaded!
downloading fileID: bf4d911d-b06e-4dff-a790-3e2eb91d7671
Files have been successfully downloaded!
downloading fileID: 07d1f9ad-1087-45ca-b672-05eca4b4f39a
Files have been successfully downloaded!
downloading fileID: a5125965-43b8-40da-946f-c3e941684e25
Files have been successfully downloaded!
downloading fileID: 21547d28-1338-4abc-8c1a-5b8007ee479e
Files have been successfully downloaded!
downloading fileID: c6c2de29-4910-4349-b526-e7cac3597f41
Files have been successfully downloaded!
downloading fileID: 010c98c7-d465-426f-8294-73947229fff4
Files have been successfully downloaded!
downloading fileID: e56b67bb-e7e2-43ce-b879-82aa2f862eb6
Files have been successfully downloaded!

## 2 Load Harmony-Processed Files & Manual Doublet Annotations

In [ ]:
def extract_celltype(path):
    """Extract cell-type name from harmony-processed h5ad filename."""
    pattern = r'-ndmm-pbmc-(.*?)-celltype-harmony-processed\.h5ad'
    match = re.search(pattern, path)
    if match:
        return match.group(1)
    return None

In [ ]:
# Path to per-cell-type Harmony-processed objects (from NB05)
input_path = "../../../data/rna/ndmm-pbmc-celltypes/"

In [ ]:
# Collect Harmony-processed h5ad files and map cell types to file paths
filenames = get_filepaths_with_glob(input_path, "*harmony-processed.h5ad")
cell_types = [extract_celltype(path) for path in filenames]
file_dict = dict(zip(cell_types, filenames))
print(f"Found {len(file_dict)} cell-type files")

['data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-gzmb+vd2gdt-celltype-harmony-processed.h5ad',
 'data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-transitionalbcell-celltype-harmony-processed.h5ad',
 'data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-gzmk-cd56dimnkcell-celltype-harmony-processed.h5ad',
 'data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-adaptivenkcell-celltype-harmony-processed.h5ad',
 'data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-isg+cd56dimnkcell-celltype-harmony-processed.h5ad']

In [ ]:
# Read manual doublet annotation spreadsheet (exported from Google Sheets)
# Contains per-cell-type Leiden clusters identified as doublets during manual review (NB06)
doublet_df = pd.read_csv("../../../data/rna/ndmm-manual-doublet-annotation-qc.csv")
print(f"Annotations for {doublet_df.shape[0]} rows")

(211, 5)

In [ ]:
# Standardize column names
doublet_df.rename(columns={
    'Celltypes (AIFI L3)': 'tidy.aifi_l3',
    'leiden cluster to remove': 'leiden_cluster_remove'
}, inplace=True)

['tidy.aifi_l3', 'leiden_cluster_remove', 'Notes', 'Relabel?', 'Genes']

In [113]:
# Select only the relevant columns: cell type and cluster labels indicating doublets
doublet_df = doublet_df[["tidy.aifi_l3", "leiden_cluster_remove"]]

# Reformat cell type names using a custom formatting function
doublet_df['tidy.aifi_l3'] = [format_cell_type(cell_type) for cell_type in doublet_df['tidy.aifi_l3']]

# Convert cluster labels to integer and then to string, keeping NaN values unchanged
doublet_df['leiden_cluster_remove'] = doublet_df['leiden_cluster_remove'].apply(
    lambda x: str(int(x)) if pd.notna(x) else x
)

doublet_df  # Display the cleaned dataframe

                                   tidy.aifi_l3 leiden_cluster_remove
0                                          ASDC                     5
1                                          ASDC                    13
2                       Activated_memory_B_cell                     6
3                       Activated_memory_B_cell                     4
4                       Activated_memory_B_cell                     5
5                              Adaptive_NK_cell                    10
6                              Adaptive_NK_cell                     9
7                              Adaptive_NK_cell                    13
8                              Adaptive_NK_cell                    11
9                                  BaEoMaP_cell                   NaN
10                         C1Qpos_CD16_monocyte                     4
11                         C1Qpos_CD16_monocyte                    12
12                         C1Qpos_CD16_monocyte                    13
13                         C1Qpos_CD16_monocyte                    14
14                                 CD14pos_cDC2                    10
15                                 CD14pos_cDC2                     3
16                                 CD14pos_cDC2                    18
17                                 CD14pos_cDC2                    19
18                      CD27pos_effector_B_cell                     8
19                      CD27pos_effector_B_cell                    13
20                      CD27neg_effector_B_cell                    11
21                      CD27neg_effector_B_cell                    13
22                      CD27neg_effector_B_cell                    15
23                                     CD4_MAIT                     7
24                                     CD4_MAIT                     2
25                           CD56bright_NK_cell                    11
26                           CD56bright_NK_cell                    14
27                           CD56bright_NK_cell                    15
28                           CD56bright_NK_cell                    13
29                           CD56bright_NK_cell                    10
30                           CD56bright_NK_cell                     5
31                                     CD8_MAIT                     9
32                                     CD8_MAIT                    12
33                                     CD8_MAIT                    13
34                                     CD8_MAIT                     3
35                                        CD8aa                     6
36                           CD95_memory_B_cell                    11
37                           CD95_memory_B_cell                    10
38                           CD95_memory_B_cell                    14
39                                     CLP_cell                    13
40                                     CLP_cell                    10
41                                     CLP_cell                    12
42                                     CLP_cell                     5
43                                CM_CD4_T_cell                    11
44                                CM_CD8_T_cell                    11
45                                CM_CD8_T_cell                    13
46                                     CMP_cell                    20
47                                     CMP_cell                    10
48                                     CMP_cell                    14
49                           Core_CD14_monocyte                     9
50                           Core_CD14_monocyte                     7
51                           Core_CD14_monocyte                    10
52                           Core_CD14_monocyte                    14
53                           Core_CD14_monocyte                    11
54                           Core_CD14_monocyte                     5
55                           Core_CD14_monocyte                     6
56                           Core_CD14_monocyte                     8
57                           Core_CD16_monocyte                    11
58                           Core_CD16_monocyte                    13
59                           Core_CD16_monocyte                     8
60                           Core_memory_B_cell                     7
61                           Core_memory_B_cell                    11
62                            Core_naive_B_cell                     7
63                            Core_naive_B_cell                    10
64                            Core_naive_B_cell                    11
65                        Core_naive_CD4_T_cell                     9
66                        Core_naive_CD4_T_cell                     5
67                        Core_naive_CD4_T_cell                    12
68                        Core_naive_CD8_T_cell                    13
69                        Core_naive_CD8_T_cell                    12
70                                    DN_T_cell                    13
71                                    DN_T_cell                    12
72                                    DN_T_cell                    11
73                          Early_memory_B_cell                     5
74                          Early_memory_B_cell                     4
75                                  Erythrocyte                    11
76                                  Erythrocyte                     3
77                                  Erythrocyte                    10
78                                  Erythrocyte                     4
79                                  Erythrocyte                     6
80                                  Erythrocyte                    13
81                                  Erythrocyte                     5
82                                  Erythrocyte                     3
83                                  Erythrocyte                     7
84                                  Erythrocyte                     9
85                              GZMBpos_Vd2_gdT                     4
86                              GZMBpos_Vd2_gdT                    10
87                GZMBneg_CD27pos_EM_CD4_T_cell                     9
88                GZMBneg_CD27pos_EM_CD4_T_cell                    11
89                GZMBneg_CD27neg_EM_CD4_T_cell                    13
90                GZMBneg_CD27neg_EM_CD4_T_cell                    10
91                GZMKpos_CD27pos_EM_CD8_T_cell                     9
92                GZMKpos_CD27pos_EM_CD8_T_cell                    11
93                GZMKpos_CD27pos_EM_CD8_T_cell                     2
94                      GZMKpos_CD56dim_NK_cell                    13
95                      GZMKpos_CD56dim_NK_cell                    16
96                      GZMKpos_CD56dim_NK_cell                    14
97                      GZMKpos_CD56dim_NK_cell                    11
98                              GZMKpos_Vd2_gdT                     5
99                              GZMKpos_Vd2_gdT                    10
100                     GZMKpos_memory_CD4_Treg                     1
101               GZMKneg_CD27pos_EM_CD8_T_cell                     3
102               GZMKneg_CD27pos_EM_CD8_T_cell                     4
103                     GZMKneg_CD56dim_NK_cell                     6
104                     GZMKneg_CD56dim_NK_cell                     9
105                     GZMKneg_CD56dim_NK_cell                     7
106                     GZMKneg_CD56dim_NK_cell                    10
107                             HLAnegDRhi_cDC2                    18
108                             HLAnegDRhi_cDC2                     6
109                             HLAnegDRhi_cDC2                    13
110                       IL1Bpos_CD14_monocyte                     2
111                       IL1Bpos_CD14_monocyte                    10
112                       IL1Bpos_CD14_monocyte                    15
113                       IL1Bpos_CD14_monocyte                    14
114                       IL1Bpos_CD14_monocyte                    17
115                                         ILC                   NaN
116                        ISGpos_CD14_monocyte                     8
117                        ISGpos_CD14_monocyte                    12
118                        ISGpos_CD14_monocyte                    13
119                        ISGpos_CD16_monocyte                     8
120                        ISGpos_CD16_monocyte                    15
121                        ISGpos_CD16_monocyte                     4
122                        ISGpos_CD16_monocyte                     6
123                        ISGpos_CD16_monocyte                    11
124                        ISGpos_CD16_monocyte                    14
125                      ISGpos_CD56dim_NK_cell                    15
126                      ISGpos_CD56dim_NK_cell                     6
127                      ISGpos_CD56dim_NK_cell                    13
128                      ISGpos_CD56dim_NK_cell                     7
129                                 ISGpos_MAIT                     7
130                                 ISGpos_cDC2                    17
131                                 ISGpos_cDC2                     5
132                                 ISGpos_cDC2                     7
133                    ISGpos_memory_CD4_T_cell                    12
134                    ISGpos_memory_CD4_T_cell                    14
135                    ISGpos_memory_CD8_T_cell                    11
136                         ISGpos_naive_B_cell                     7
137                         ISGpos_naive_B_cell                     6
138                     ISGpos_naive_CD4_T_cell                    13
139                     ISGpos_naive_CD4_T_cell                    14
140                     ISGpos_naive_CD4_T_cell                    10
141                     ISGpos_naive_CD4_T_cell                    11
142                     ISGpos_naive_CD8_T_cell                     9
143                     ISGpos_naive_CD8_T_cell                    10
144                     ISGpos_naive_CD8_T_cell                    11
145                       Intermediate_monocyte                     6
146                       Intermediate_monocyte                    15
147                    KLRB1pos_memory_CD4_Treg                     6
148                    KLRB1pos_memory_CD4_Treg                    15
149                    KLRB1pos_memory_CD8_Treg                     1
150                    KLRB1pos_memory_CD8_Treg                    13
151                    KLRB1pos_memory_CD8_Treg                    17
152      KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell                    10
153      KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell                     7
154      KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell                     9
155                   KLRF1pos_effector_Vd1_gdT                     6
156                   KLRF1pos_effector_Vd1_gdT                     5
157                   KLRF1pos_effector_Vd1_gdT                     7
158      KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell                     3
159      KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell                     9
160      KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell                    10
161  KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell                     8
162  KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell                     7
163                   KLRF1neg_effector_Vd1_gdT                     2
164                   KLRF1neg_effector_Vd1_gdT                    11
165                   KLRF1neg_effector_Vd1_gdT                    10
166                   KLRF1neg_effector_Vd1_gdT                     3
167                             Memory_CD4_Treg                    12
168                             Memory_CD4_Treg                    11
169                             Memory_CD8_Treg                     3
170                             Memory_CD8_Treg                     4
171                              Naive_CD4_Treg                     8
172                              Naive_CD4_Treg                    10
173                               Naive_Vd1_gdT                   NaN
174                                 Plasma_cell                    11
175                                 Plasma_cell                    14
176                                 Plasma_cell                    13
177                                 Plasma_cell                    15
178                                 Plasma_cell                     9
179                                    Platelet                    15
180                                    Platelet                     5
181                                    Platelet                    13
182                                    Platelet                    12
183                                    Platelet                    10
184                       Proliferating_NK_cell                     6
185                       Proliferating_NK_cell                    16
186                       Proliferating_NK_cell                    17
187                       Proliferating_NK_cell                     9
188                        Proliferating_T_cell                    15
189                        Proliferating_T_cell                    22
190                        Proliferating_T_cell                    19
191                        Proliferating_T_cell                    20
192                             SOX4pos_Vd1_gdT                   NaN
193                    SOX4pos_naive_CD4_T_cell                     6
194                    SOX4pos_naive_CD4_T_cell                     5
195                    SOX4pos_naive_CD8_T_cell                     2
196                         Transitional_B_cell                    11
197                         Transitional_B_cell                    12
198                         Transitional_B_cell                    13
199              Type_2_polarized_memory_B_cell                     6
200                                        cDC1                    12
201                                        cDC1                    15
202                                        cDC1                     3
203                                        cDC1                    10
204                                        cDC1                    13
205                                         pDC                    12
206                                         pDC                    13
207                                         pDC                    14
208                                         pDC                    16
209                                         pDC                    17
210                                         pDC                    11

In [ ]:
# Exclude clusters 5, 6, 8 from Core CD14 monocyte doublet removal
# These clusters are being RELABELED to Other_DC, not removed as doublets
doublet_df = doublet_df[~(
    (doublet_df['tidy.aifi_l3'] == 'Core_CD14_monocyte') &
    (doublet_df['leiden_cluster_remove'].isin(['5', '6', '8']))
)]

In [129]:
len(doublet_df['tidy.aifi_l3'].unique().tolist())

71

In [130]:
doublet_df

                                   tidy.aifi_l3 leiden_cluster_remove
0                                          ASDC                     5
1                                          ASDC                    13
2                       Activated_memory_B_cell                     6
3                       Activated_memory_B_cell                     4
4                       Activated_memory_B_cell                     5
5                              Adaptive_NK_cell                    10
6                              Adaptive_NK_cell                     9
7                              Adaptive_NK_cell                    13
8                              Adaptive_NK_cell                    11
9                                  BaEoMaP_cell                   NaN
10                         C1Qpos_CD16_monocyte                     4
11                         C1Qpos_CD16_monocyte                    12
12                         C1Qpos_CD16_monocyte                    13
13                         C1Qpos_CD16_monocyte                    14
14                                 CD14pos_cDC2                    10
15                                 CD14pos_cDC2                     3
16                                 CD14pos_cDC2                    18
17                                 CD14pos_cDC2                    19
18                      CD27pos_effector_B_cell                     8
19                      CD27pos_effector_B_cell                    13
20                      CD27neg_effector_B_cell                    11
21                      CD27neg_effector_B_cell                    13
22                      CD27neg_effector_B_cell                    15
23                                     CD4_MAIT                     7
24                                     CD4_MAIT                     2
25                           CD56bright_NK_cell                    11
26                           CD56bright_NK_cell                    14
27                           CD56bright_NK_cell                    15
28                           CD56bright_NK_cell                    13
29                           CD56bright_NK_cell                    10
30                           CD56bright_NK_cell                     5
31                                     CD8_MAIT                     9
32                                     CD8_MAIT                    12
33                                     CD8_MAIT                    13
34                                     CD8_MAIT                     3
35                                        CD8aa                     6
36                           CD95_memory_B_cell                    11
37                           CD95_memory_B_cell                    10
38                           CD95_memory_B_cell                    14
39                                     CLP_cell                    13
40                                     CLP_cell                    10
41                                     CLP_cell                    12
42                                     CLP_cell                     5
43                                CM_CD4_T_cell                    11
44                                CM_CD8_T_cell                    11
45                                CM_CD8_T_cell                    13
46                                     CMP_cell                    20
47                                     CMP_cell                    10
48                                     CMP_cell                    14
49                           Core_CD14_monocyte                     9
50                           Core_CD14_monocyte                     7
51                           Core_CD14_monocyte                    10
52                           Core_CD14_monocyte                    14
53                           Core_CD14_monocyte                    11
57                           Core_CD16_monocyte                    11
58                           Core_CD16_monocyte                    13
59                           Core_CD16_monocyte                     8
60                           Core_memory_B_cell                     7
61                           Core_memory_B_cell                    11
62                            Core_naive_B_cell                     7
63                            Core_naive_B_cell                    10
64                            Core_naive_B_cell                    11
65                        Core_naive_CD4_T_cell                     9
66                        Core_naive_CD4_T_cell                     5
67                        Core_naive_CD4_T_cell                    12
68                        Core_naive_CD8_T_cell                    13
69                        Core_naive_CD8_T_cell                    12
70                                    DN_T_cell                    13
71                                    DN_T_cell                    12
72                                    DN_T_cell                    11
73                          Early_memory_B_cell                     5
74                          Early_memory_B_cell                     4
75                                  Erythrocyte                    11
76                                  Erythrocyte                     3
77                                  Erythrocyte                    10
78                                  Erythrocyte                     4
79                                  Erythrocyte                     6
80                                  Erythrocyte                    13
81                                  Erythrocyte                     5
82                                  Erythrocyte                     3
83                                  Erythrocyte                     7
84                                  Erythrocyte                     9
85                              GZMBpos_Vd2_gdT                     4
86                              GZMBpos_Vd2_gdT                    10
87                GZMBneg_CD27pos_EM_CD4_T_cell                     9
88                GZMBneg_CD27pos_EM_CD4_T_cell                    11
89                GZMBneg_CD27neg_EM_CD4_T_cell                    13
90                GZMBneg_CD27neg_EM_CD4_T_cell                    10
91                GZMKpos_CD27pos_EM_CD8_T_cell                     9
92                GZMKpos_CD27pos_EM_CD8_T_cell                    11
93                GZMKpos_CD27pos_EM_CD8_T_cell                     2
94                      GZMKpos_CD56dim_NK_cell                    13
95                      GZMKpos_CD56dim_NK_cell                    16
96                      GZMKpos_CD56dim_NK_cell                    14
97                      GZMKpos_CD56dim_NK_cell                    11
98                              GZMKpos_Vd2_gdT                     5
99                              GZMKpos_Vd2_gdT                    10
100                     GZMKpos_memory_CD4_Treg                     1
101               GZMKneg_CD27pos_EM_CD8_T_cell                     3
102               GZMKneg_CD27pos_EM_CD8_T_cell                     4
103                     GZMKneg_CD56dim_NK_cell                     6
104                     GZMKneg_CD56dim_NK_cell                     9
105                     GZMKneg_CD56dim_NK_cell                     7
106                     GZMKneg_CD56dim_NK_cell                    10
107                             HLAnegDRhi_cDC2                    18
108                             HLAnegDRhi_cDC2                     6
109                             HLAnegDRhi_cDC2                    13
110                       IL1Bpos_CD14_monocyte                     2
111                       IL1Bpos_CD14_monocyte                    10
112                       IL1Bpos_CD14_monocyte                    15
113                       IL1Bpos_CD14_monocyte                    14
114                       IL1Bpos_CD14_monocyte                    17
115                                         ILC                   NaN
116                        ISGpos_CD14_monocyte                     8
117                        ISGpos_CD14_monocyte                    12
118                        ISGpos_CD14_monocyte                    13
119                        ISGpos_CD16_monocyte                     8
120                        ISGpos_CD16_monocyte                    15
121                        ISGpos_CD16_monocyte                     4
122                        ISGpos_CD16_monocyte                     6
123                        ISGpos_CD16_monocyte                    11
124                        ISGpos_CD16_monocyte                    14
125                      ISGpos_CD56dim_NK_cell                    15
126                      ISGpos_CD56dim_NK_cell                     6
127                      ISGpos_CD56dim_NK_cell                    13
128                      ISGpos_CD56dim_NK_cell                     7
129                                 ISGpos_MAIT                     7
130                                 ISGpos_cDC2                    17
131                                 ISGpos_cDC2                     5
132                                 ISGpos_cDC2                     7
133                    ISGpos_memory_CD4_T_cell                    12
134                    ISGpos_memory_CD4_T_cell                    14
135                    ISGpos_memory_CD8_T_cell                    11
136                         ISGpos_naive_B_cell                     7
137                         ISGpos_naive_B_cell                     6
138                     ISGpos_naive_CD4_T_cell                    13
139                     ISGpos_naive_CD4_T_cell                    14
140                     ISGpos_naive_CD4_T_cell                    10
141                     ISGpos_naive_CD4_T_cell                    11
142                     ISGpos_naive_CD8_T_cell                     9
143                     ISGpos_naive_CD8_T_cell                    10
144                     ISGpos_naive_CD8_T_cell                    11
145                       Intermediate_monocyte                     6
146                       Intermediate_monocyte                    15
147                    KLRB1pos_memory_CD4_Treg                     6
148                    KLRB1pos_memory_CD4_Treg                    15
149                    KLRB1pos_memory_CD8_Treg                     1
150                    KLRB1pos_memory_CD8_Treg                    13
151                    KLRB1pos_memory_CD8_Treg                    17
152      KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell                    10
153      KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell                     7
154      KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell                     9
155                   KLRF1pos_effector_Vd1_gdT                     6
156                   KLRF1pos_effector_Vd1_gdT                     5
157                   KLRF1pos_effector_Vd1_gdT                     7
158      KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell                     3
159      KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell                     9
160      KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell                    10
161  KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell                     8
162  KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell                     7
163                   KLRF1neg_effector_Vd1_gdT                     2
164                   KLRF1neg_effector_Vd1_gdT                    11
165                   KLRF1neg_effector_Vd1_gdT                    10
166                   KLRF1neg_effector_Vd1_gdT                     3
167                             Memory_CD4_Treg                    12
168                             Memory_CD4_Treg                    11
169                             Memory_CD8_Treg                     3
170                             Memory_CD8_Treg                     4
171                              Naive_CD4_Treg                     8
172                              Naive_CD4_Treg                    10
173                               Naive_Vd1_gdT                   NaN
174                                 Plasma_cell                    11
175                                 Plasma_cell                    14
176                                 Plasma_cell                    13
177                                 Plasma_cell                    15
178                                 Plasma_cell                     9
179                                    Platelet                    15
180                                    Platelet                     5
181                                    Platelet                    13
182                                    Platelet                    12
183                                    Platelet                    10
184                       Proliferating_NK_cell                     6
185                       Proliferating_NK_cell                    16
186                       Proliferating_NK_cell                    17
187                       Proliferating_NK_cell                     9
188                        Proliferating_T_cell                    15
189                        Proliferating_T_cell                    22
190                        Proliferating_T_cell                    19
191                        Proliferating_T_cell                    20
192                             SOX4pos_Vd1_gdT                   NaN
193                    SOX4pos_naive_CD4_T_cell                     6
194                    SOX4pos_naive_CD4_T_cell                     5
195                    SOX4pos_naive_CD8_T_cell                     2
196                         Transitional_B_cell                    11
197                         Transitional_B_cell                    12
198                         Transitional_B_cell                    13
199              Type_2_polarized_memory_B_cell                     6
200                                        cDC1                    12
201                                        cDC1                    15
202                                        cDC1                     3
203                                        cDC1                    10
204                                        cDC1                    13
205                                         pDC                    12
206                                         pDC                    13
207                                         pDC                    14
208                                         pDC                    16
209                                         pDC                    17
210                                         pDC                    11

### 2.1 Collapse Leiden Clusters per Cell Type

In [ ]:
# Group by cell type and aggregate Leiden clusters to remove into lists
collapsed_df = doublet_df.groupby('tidy.aifi_l3')['leiden_cluster_remove'].agg(
    lambda x: list(x) if not x.isnull().all() else np.nan
).reset_index()

pd.set_option('display.max_rows', None)
collapsed_df

,tidy.aifi_l3,leiden_cluster_remove
0,ASDC,"[5, 13]"
1,Activated_memory_B_cell,"[6, 4, 5]"
2,Adaptive_NK_cell,"[10, 9, 13, 11]"
3,BaEoMaP_cell,NaN
4,C1Qpos_CD16_monocyte,"[4, 12, 13, 14]"
5,CD14pos_cDC2,"[10, 3, 18, 19]"
6,CD27neg_effector_B_cell,"[11, 13, 15]"
7,CD27pos_effector_B_cell,"[8, 13]"
8,CD4_MAIT,"[7, 2]"
9,CD56bright_NK_cell,"[11, 14, 15, 13, 10, 5]"
10,CD8_MAIT,"[9, 12, 13, 3]"
11,CD8aa,[6]
12,CD95_memory_B_cell,"[11, 10, 14]"
13,CLP_cell,"[13, 10, 12, 5]"
14,CMP_cell,"[20, 10, 14]"
15,CM_CD4_T_cell,[11]
16,CM_CD8_T_cell,"[11, 13]"
17,Core_CD14_monocyte,"[9, 7, 10, 14, 11]"
18,Core_CD16_monocyte,"[11, 13, 8]"
19,Core_memory_B_cell,"[7, 11]"
20,Core_naive_B_cell,"[7, 10, 11]"
21,Core_naive_CD4_T_cell,"[9, 5, 12]"
22,Core_naive_CD8_T_cell,"[13, 12]"
23,DN_T_cell,"[13, 12, 11]"
24,Early_memory_B_cell,"[5, 4]"
25,Erythrocyte,"[11, 3, 10, 4, 6, 13, 5, 3, 7, 9]"
26,GZMBneg_CD27neg_EM_CD4_T_cell,"[13, 10]"
27,GZMBneg_CD27pos_EM_CD4_T_cell,"[9, 11]"
28,GZMBpos_Vd2_gdT,"[4, 10]"
29,GZMKneg_CD27pos_EM_CD8_T_cell,"[3, 4]"
30,GZMKneg_CD56dim_NK_cell,"[6, 9, 7, 10]"
31,GZMKpos_CD27pos_EM_CD8_T_cell,"[9, 11, 2]"
32,GZMKpos_CD56dim_NK_cell,"[13, 16, 14, 11]"
33,GZMKpos_Vd2_gdT,"[5, 10]"
34,GZMKpos_memory_CD4_Treg,[1]
35,HLAnegDRhi_cDC2,"[18, 6, 13]"
36,IL1Bpos_CD14_monocyte,"[2, 10, 15, 14, 17]"
37,ILC,NaN
38,ISGpos_CD14_monocyte,"[8, 12, 13]"
39,ISGpos_CD16_monocyte,"[8, 15, 4, 6, 11, 14]"
40,ISGpos_CD56dim_NK_cell,"[15, 6, 13, 7]"
41,ISGpos_MAIT,[7]
42,ISGpos_cDC2,"[17, 5, 7]"
43,ISGpos_memory_CD4_T_cell,"[12, 14]"
44,ISGpos_memory_CD8_T_cell,[11]
45,ISGpos_naive_B_cell,"[7, 6]"
46,ISGpos_naive_CD4_T_cell,"[13, 14, 10, 11]"
47,ISGpos_naive_CD8_T_cell,"[9, 10, 11]"
48,Intermediate_monocyte,"[6, 15]"
49,KLRB1pos_memory_CD4_Treg,"[6, 15]"
50,KLRB1pos_memory_CD8_Treg,"[1, 13, 17]"
51,KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell,"[3, 9, 10]"
52,KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell,"[8, 7]"
53,KLRF1neg_effector_Vd1_gdT,"[2, 11, 10, 3]"
54,KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell,"[10, 7, 9]"
55,KLRF1pos_effector_Vd1_gdT,"[6, 5, 7]"
56,Memory_CD4_Treg,"[12, 11]"
57,Memory_CD8_Treg,"[3, 4]"
58,Naive_CD4_Treg,"[8, 10]"
59,Naive_Vd1_gdT,NaN
60,Plasma_cell,"[11, 14, 13, 15, 9]"
61,Platelet,"[15, 5, 13, 12, 10]"
62,Proliferating_NK_cell,"[6, 16, 17, 9]"
63,Proliferating_T_cell,"[15, 22, 19, 20]"
64,SOX4pos_Vd1_gdT,NaN
65,SOX4pos_naive_CD4_T_cell,"[6, 5]"
66,SOX4pos_naive_CD8_T_cell,[2]
67,Transitional_B_cell,"[11, 12, 13]"
68,Type_2_polarized_memory_B_cell,[6]
69,cDC1,"[12, 15, 3, 10, 13]"
70,pDC,"[12, 13, 14, 16, 17, 11]"

In [134]:
unique_celltypes = collapsed_df['tidy.aifi_l3'].unique()

In [ ]:
def to_marker_style(cell_type):
    """Convert formatted cell-type name to lowercase marker-style key for dict lookup."""
    cell_type = cell_type.replace('_', '').replace('pos', '+').replace('neg', '-')
    return cell_type.lower()

# Map original cell-type names to marker-style keys used in file_dict
unique_celltypes = collapsed_df['tidy.aifi_l3'].unique()
collapsed_df['marker_style'] = collapsed_df['tidy.aifi_l3'].map(
    {ct: to_marker_style(ct) for ct in unique_celltypes}
)

### 2.2 Build Doublet Cluster Dictionary

In [ ]:
# Build dict: marker_style_key → list of Leiden cluster IDs to remove
doublet_cluster_dict = {}
for _, row in collapsed_df.iterrows():
    key = row['marker_style']
    val = row['leiden_cluster_remove']

    if isinstance(val, list):
        values = [str(int(x)) for x in val if pd.notna(x)]
    elif isinstance(val, str):
        values = val.split(',')
    else:
        values = []

    doublet_cluster_dict[key] = values

print(f"{len(doublet_cluster_dict)} cell types with annotations")

{'asdc': ['5', '13'], 'activatedmemorybcell': ['6', '4', '5'], 'adaptivenkcell': ['10', '9', '13', '11'], 'baeomapcell': [], 'c1q+cd16monocyte': ['4', '12', '13', '14'], 'cd14+cdc2': ['10', '3', '18', '19'], 'cd27-effectorbcell': ['11', '13', '15'], 'cd27+effectorbcell': ['8', '13'], 'cd4mait': ['7', '2'], 'cd56brightnkcell': ['11', '14', '15', '13', '10', '5'], 'cd8mait': ['9', '12', '13', '3'], 'cd8aa': ['6'], 'cd95memorybcell': ['11', '10', '14'], 'clpcell': ['13', '10', '12', '5'], 'cmpcell': ['20', '10', '14'], 'cmcd4tcell': ['11'], 'cmcd8tcell': ['11', '13'], 'corecd14monocyte': ['9', '7', '10', '14', '11'], 'corecd16monocyte': ['11', '13', '8'], 'corememorybcell': ['7', '11'], 'corenaivebcell': ['7', '10', '11'], 'corenaivecd4tcell': ['9', '5', '12'], 'corenaivecd8tcell': ['13', '12'], 'dntcell': ['13', '12', '11'], 'earlymemorybcell': ['5', '4'], 'erythrocyte': ['11', '3', '10', '4', '6', '13', '5', '3', '7', '9'], 'gzmb-cd27-emcd4tcell': ['13', '10'], 'gzmb-cd27+emcd4tcell': ['9', '11'], 'gzmb+vd2gdt': ['4', '10'], 'gzmk-cd27+emcd8tcell': ['3', '4'], 'gzmk-cd56dimnkcell': ['6', '9', '7', '10'], 'gzmk+cd27+emcd8tcell': ['9', '11', '2'], 'gzmk+cd56dimnkcell': ['13', '16', '14', '11'], 'gzmk+vd2gdt': ['5', '10'], 'gzmk+memorycd4treg': ['1'], 'hla-drhicdc2': ['18', '6', '13'], 'il1b+cd14monocyte': ['2', '10', '15', '14', '17'], 'ilc': [], 'isg+cd14monocyte': ['8', '12', '13'], 'isg+cd16monocyte': ['8', '15', '4', '6', '11', '14'], 'isg+cd56dimnkcell': ['15', '6', '13', '7'], 'isg+mait': ['7'], 'isg+cdc2': ['17', '5', '7'], 'isg+memorycd4tcell': ['12', '14'], 'isg+memorycd8tcell': ['11'], 'isg+naivebcell': ['7', '6'], 'isg+naivecd4tcell': ['13', '14', '10', '11'], 'isg+naivecd8tcell': ['9', '10', '11'], 'intermediatemonocyte': ['6', '15'], 'klrb1+memorycd4treg': ['6', '15'], 'klrb1+memorycd8treg': ['1', '13', '17'], 'klrf1-gzmb+cd27-emcd8tcell': ['3', '9', '10'], 'klrf1-gzmb+cd27-memorycd4tcell': ['8', '7'], 'klrf1-effectorvd1gdt': ['2', '11', '10', '3'], 'klrf1+gzmb+cd27-emcd8tcell': ['10', '7', '9'], 'klrf1+effectorvd1gdt': ['6', '5', '7'], 'memorycd4treg': ['12', '11'], 'memorycd8treg': ['3', '4'], 'naivecd4treg': ['8', '10'], 'naivevd1gdt': [], 'plasmacell': ['11', '14', '13', '15', '9'], 'platelet': ['15', '5', '13', '12', '10'], 'proliferatingnkcell': ['6', '16', '17', '9'], 'proliferatingtcell': ['15', '22', '19', '20'], 'sox4+vd1gdt': [], 'sox4+naivecd4tcell': ['6', '5'], 'sox4+naivecd8tcell': ['2'], 'transitionalbcell': ['11', '12', '13'], 'type2polarizedmemorybcell': ['6'], 'cdc1': ['12', '15', '3', '10', '13'], 'pdc': ['12', '13', '14', '16', '17', '11']}

## 3 Generate Deep-Cleaned Objects per Cell Type

In [ ]:
out_files = []   # Track exported h5ad paths
meta_list = []   # Accumulate per-cell-type metadata DataFrames

for label, file in file_dict.items():
    print("Key:", label)
    print("Value:", file)

    # Read the h5ad file
    adata = sc.read_h5ad(file)
    print(adata)

    # --- Relabel Core CD14 monocyte Leiden clusters 5, 6, 8 → Other_DC ---
    # These clusters express DC markers and were misclassified as monocytes
    if 'Other_DC' not in adata.obs['tidy.aifi_l3'].cat.categories:
        adata.obs['tidy.aifi_l3'] = adata.obs['tidy.aifi_l3'].cat.add_categories(['Other_DC'])

    mask = (
        (adata.obs['tidy.aifi_l3'] == 'Core CD14 monocyte') &
        (adata.obs['leiden'].isin(['5', '6', '8']))
    )
    adata.obs.loc[mask, 'tidy.aifi_l3'] = 'Other_DC'

    # --- Mark doublet clusters based on manual annotation ---
    doublet_clust = doublet_cluster_dict.get(label, [])
    print(f"  Doublet clusters: {doublet_clust}")

    if len(doublet_clust) == 0:
        adata.obs['doublets_manual'] = 'no'
    else:
        adata.obs['doublets_manual'] = [
            'yes' if leiden in doublet_clust else 'no'
            for leiden in adata.obs['leiden']
        ]

    print(pd.crosstab(adata.obs['doublets_manual'], adata.obs['leiden']))

    # Collect metadata
    meta = adata.obs
    meta_list.append(meta)
    meta.to_csv(os.path.join(out_dir, f'ndmm_doublet_meta_{label}_{date.today()}.csv'))

    # Subset to singlets only and export cleaned object
    adata_subset = adata[adata.obs['doublets_manual'] == 'no']
    print(f"  Cells retained: {adata_subset.shape[0]:,}")

    out_file = os.path.join(out_dir, f'ndmm_deepcleaned_{label}_{date.today()}.h5ad')
    adata_subset.write_h5ad(out_file)
    out_files.append(out_file)
    print("_" * 65)

Key: gzmb+vd2gdt
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-gzmb+vd2gdt-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 9351 × 2845
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['4', '10']
leiden              0     1    2    3    4    5    6    7    8    9   10
doublets_manual
no               2165  1819  893  845    0  630  551  537  470  386    0
yes                 0     0    0    0  718    0    0    0    0    0  337
Subsetted cells to: (8296, 2845)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: transitionalbcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-transitionalbcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 30546 × 2876
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['11', '12', '13']
leiden              0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               4540  3823  3549  3334  2997  2219  2128  1549  1509  1302
yes                 0     0     0     0     0     0     0     0     0     0

leiden             10    11   12   13
doublets_manual
no               1142     0    0    0
yes                 0  1095  850  509
Subsetted cells to: (28092, 2876)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: gzmk-cd56dimnkcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-gzmk-cd56dimnkcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 180135 × 1761
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['6', '9', '7', '10']
leiden               0      1      2      3      4      5      6     7     8  \
doublets_manual
no               35989  29486  26885  21453  16534  16219      0     0  6228
yes                  0      0      0      0      0      0  10260  9933     0

leiden              9    10
doublets_manual
no                  0     0
yes              5206  1942
Subsetted cells to: (152794, 1761)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: adaptivenkcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-adaptivenkcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 60378 × 2200
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['10', '9', '13', '11']
leiden              0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               8612  8273  8267  6667  5691  5305  3449  3178  3114     0
yes                 0     0     0     0     0     0     0     0     0  2564

leiden             10    11   12   13
doublets_manual
no                  0     0  604    0
yes              2556  1726    0  372
Subsetted cells to: (53160, 2200)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: isg+cd56dimnkcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-isg+cd56dimnkcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 10820 × 4021
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['15', '6', '13', '7']
leiden              0     1     2    3    4    5    6    7    8    9   10  \
doublets_manual
no               2108  1681  1333  946  874  814    0    0  429  303  293
yes                 0     0     0    0    0    0  542  471    0    0    0

leiden            11   12   13   14   15
doublets_manual
no               292  288    0  150    0
yes                0    0  152    0  144
Subsetted cells to: (9511, 4021)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: gzmk+cd27+emcd8tcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-gzmk+cd27+emcd8tcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 264574 × 1534
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['9', '11', '2']
leiden               0      1      2      3      4      5      6      7  \
doublets_manual
no               38909  38017      0  30096  25720  25581  22450  20719
yes                  0      0  36564      0      0      0      0      0

leiden               8     9    10   11
doublets_manual
no               15579     0  4260    0
yes                  0  6165     0  514
Subsetted cells to: (221331, 1534)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: clpcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-clpcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 502 × 4351
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['13', '10', '12', '5']
leiden            0   1   2   3   4   5   6   7   8   9  10  11  12  13
doublets_manual
no               70  53  45  42  41   0  38  36  35  26   0  23   0   0
yes               0   0   0   0   0  40   0   0   0   0  23   0  18  12
Subsetted cells to: (409, 4351)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: baeomapcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-baeomapcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 170 × 4736
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: []
The list is empty
leiden            0   1   2   3   4   5
doublets_manual
no               36  33  28  28  27  18
Subsetted cells to: (170, 4736)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: il1b+cd14monocyte
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-il1b+cd14monocyte-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 67464 × 2609
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['2', '10', '15', '14', '17']
leiden              0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               7035  6630     0  6312  5997  5379  5257  5098  4952  4828
yes                 0     0  6615     0     0     0     0     0     0     0

leiden             10    11    12   13   14   15   16   17
doublets_manual
no                  0  1952  1874  932    0    0  470    0
yes              2438     0     0    0  932  499    0  264
Subsetted cells to: (56716, 2609)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: cd8mait
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-cd8mait-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 15097 × 2324
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['9', '12', '13', '3']
leiden              0     1     2     3     4    5    6    7    8    9   10  \
doublets_manual
no               3273  2329  1739     0  1108  812  752  717  662    0  549
yes                 0     0     0  1490     0    0    0    0    0  584    0

leiden            11   12   13
doublets_manual
no               451    0    0
yes                0  334  297
Subsetted cells to: (12392, 2324)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: c1q+cd16monocyte
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-c1q+cd16monocyte-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 11829 × 3137
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['4', '12', '13', '14']
leiden              0     1     2     3    4    5    6    7    8    9   10  \
doublets_manual
no               2097  1807  1426  1219    0  887  784  777  486  415  378
yes                 0     0     0     0  894    0    0    0    0    0    0

leiden            11   12   13  14
doublets_manual
no               262    0    0   0
yes                0  222  122  53
Subsetted cells to: (10538, 3137)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: proliferatingtcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-proliferatingtcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 14486 × 3625
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['15', '22', '19', '20']
leiden              0     1     2     3     4     5    6    7    8    9  ...  \
doublets_manual                                                          ...
no               1749  1468  1462  1247  1218  1180  727  685  666  611  ...
yes                 0     0     0     0     0     0    0    0    0    0  ...

leiden            13   14   15   16   17   18   19   20  21  22
doublets_manual
no               386  365    0  254  154  149    0    0  96   0
yes                0    0  334    0    0    0  145  140   0  67

[2 rows x 23 columns]
Subsetted cells to: (13800, 3625)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: corememorybcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-corememorybcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 15179 × 2884
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['7', '11']
leiden              0     1     2     3     4     5    6    7    8    9   10  \
doublets_manual
no               2436  2359  2265  1740  1598  1523  724    0  562  414  358
yes                 0     0     0     0     0     0    0  570    0    0    0

leiden            11   12   13
doublets_manual
no                 0  214  194
yes              222    0    0
Subsetted cells to: (14387, 2884)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: isg+memorycd8tcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-isg+memorycd8tcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 2105 × 3696
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['11']
leiden             0    1    2    3    4    5    6    7   8   9  10  11  12  \
doublets_manual
no               341  271  240  166  156  142  135  122  97  86  74   0  60
yes                0    0    0    0    0    0    0    0   0   0   0  65   0

leiden           13  14  15  16
doublets_manual
no               53  49  33  15
yes               0   0   0   0
Subsetted cells to: (2040, 3696)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: isg+cdc2
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-isg+cdc2-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 2119 × 3736
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['17', '5', '7']
leiden             0    1    2    3    4    5   6   7   8   9  10  11  12  13  \
doublets_manual
no               369  340  240  208  120    0  89   0  81  79  78  72  72  59
yes                0    0    0    0    0  101   0  87   0   0   0   0   0   0

leiden           14  15  16  17
doublets_manual
no               54  29  27   0
yes               0   0   0  14
Subsetted cells to: (1917, 3736)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: dntcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-dntcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 6893 × 3920
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['13', '12', '11']
leiden              0    1    2    3    4    5    6    7    8    9   10   11  \
doublets_manual
no               1127  962  743  735  580  478  461  400  380  210  175    0
yes                 0    0    0    0    0    0    0    0    0    0    0  170

leiden            12   13   14  15  16
doublets_manual
no                 0    0  103  84  49
yes              125  111    0   0   0
Subsetted cells to: (6487, 3920)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: isg+cd14monocyte
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-isg+cd14monocyte-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 79831 × 2926
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['8', '12', '13']
leiden               0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               10521  9236  8411  8024  7637  6974  5934  5531     0  5121
yes                  0     0     0     0     0     0     0     0  5507     0

leiden             10    11    12   13
doublets_manual
no               3047  1994     0    0
yes                 0     0  1452  442
Subsetted cells to: (72430, 2926)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: isg+naivecd8tcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-isg+naivecd8tcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 552 × 3323
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['9', '10', '11']
leiden             0    1   2   3   4   5   6   7   8   9  10  11
doublets_manual
no               134  115  48  37  34  33  29  27  26   0   0   0
yes                0    0   0   0   0   0   0   0   0  24  23  22
Subsetted cells to: (483, 3323)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: cd56brightnkcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-cd56brightnkcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 33378 × 2970
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['11', '14', '15', '13', '10', '5']
leiden              0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               5129  5086  3171  2924  2879     0  2515  2065  2019  1099
yes                 0     0     0     0     0  2588     0     0     0     0

leiden            10   11   12   13   14   15
doublets_manual
no                 0    0  820    0    0    0
yes              942  822    0  657  367  295
Subsetted cells to: (27707, 2970)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: memorycd4treg
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-memorycd4treg-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 60594 × 2302
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['12', '11']
leiden              0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               7948  6092  5896  5879  5842  5600  5389  5257  3686  2701
yes                 0     0     0     0     0     0     0     0     0     0

leiden             10    11    12    13
doublets_manual
no               1940     0     0  1260
yes                 0  1609  1495     0
Subsetted cells to: (57490, 2302)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: klrf1-gzmb+cd27-memorycd4tcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-klrf1-gzmb+cd27-memorycd4tcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 51265 × 1921
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['8', '7']
leiden              0     1     2     3     4     5     6     7     8    9
doublets_manual
no               9253  8766  7064  6776  5745  4533  3717     0     0  597
yes                 0     0     0     0     0     0     0  3621  1193    0
Subsetted cells to: (46451, 1921)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: pdc
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-pdc-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 7638 × 3538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['12', '13', '14', '16', '17', '11']
leiden              0     1    2    3    4    5    6    7    8    9   10   11  \
doublets_manual
no               1224  1016  665  616  491  470  442  428  411  292  275    0
yes                 0     0    0    0    0    0    0    0    0    0    0  273

leiden            12   13   14   15  16  17
doublets_manual
no                 0    0    0  190   0   0
yes              257  235  214    0  93  46
Subsetted cells to: (6520, 3538)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ilc
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-ilc-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 309 × 4315
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: []
The list is empty
leiden            0   1   2   3   4   5   6
doublets_manual
no               65  53  49  41  39  34  28
Subsetted cells to: (309, 4315)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: platelet
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-platelet-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 26497 × 3051
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['15', '5', '13', '12', '10']
leiden              0     1     2     3     4     5     6     7    8    9  \
doublets_manual
no               5787  3499  2921  2763  2642     0  1963  1561  694  543
yes                 0     0     0     0     0  2413     0     0    0    0

leiden            10   11   12   13   14   15
doublets_manual
no                 0  359    0    0  192    0
yes              535    0  266  220    0  139
Subsetted cells to: (22924, 3051)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: corenaivecd4tcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-corenaivecd4tcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 341020 × 1598
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['9', '5', '12']
leiden               0      1      2      3      4      5      6      7  \
doublets_manual
no               41755  41583  40844  39836  33451      0  32753  30144
yes                  0      0      0      0      0  33318      0      0

leiden               8      9    10    11    12
doublets_manual
no               13622      0  9625  8291     0
yes                  0  10687     0     0  5111
Subsetted cells to: (291904, 1598)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: klrf1-effectorvd1gdt
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-klrf1-effectorvd1gdt-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 3733 × 3841
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['2', '11', '10', '3']
leiden             0    1    2    3    4    5    6    7    8    9  10  11  12
doublets_manual
no               800  520    0    0  269  260  218  217  150  149   0   0  42
yes                0    0  518  487    0    0    0    0    0    0  56  47   0
Subsetted cells to: (2625, 3841)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: gzmk+cd56dimnkcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-gzmk+cd56dimnkcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 33226 × 2821
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['13', '16', '14', '11']
leiden              0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               4131  3954  3529  2985  2911  2645  2266  1695  1462  1421
yes                 0     0     0     0     0     0     0     0     0     0

leiden             10    11    12   13   14   15   16
doublets_manual
no               1377     0  1085    0    0  542    0
yes                 0  1280     0  873  756    0  314
Subsetted cells to: (30003, 2821)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: gzmk+vd2gdt
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-gzmk+vd2gdt-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 5103 × 2857
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['5', '10']
leiden             0    1    2    3    4    5    6    7    8    9   10   11  \
doublets_manual
no               917  842  470  409  344    0  266  255  250  230    0  229
yes                0    0    0    0    0  310    0    0    0    0  229    0

leiden            12   13  14
doublets_manual
no               175  111  66
yes                0    0   0
Subsetted cells to: (4564, 2857)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: sox4+naivecd8tcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-sox4+naivecd8tcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 287 × 3961
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['2']
leiden            0   1   2   3   4   5   6   7
doublets_manual
no               76  56   0  33  22  21  15  14
yes               0   0  50   0   0   0   0   0
Subsetted cells to: (237, 3961)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: gzmb-cd27+emcd4tcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-gzmb-cd27+emcd4tcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 71344 × 1993
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['9', '11']
leiden               0      1     2     3     4     5     6     7     8     9  \
doublets_manual
no               10786  10218  9654  8982  8606  8159  6562  2586  2199     0
yes                  0      0     0     0     0     0     0     0     0  1304

leiden             10   11
doublets_manual
no               1297    0
yes                 0  991
Subsetted cells to: (69049, 1993)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: gzmb-cd27-emcd4tcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-gzmb-cd27-emcd4tcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 80694 × 2111
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['13', '10']
leiden               0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               10675  9284  8276  8068  6965  6806  6406  6367  4171  3858
yes                  0     0     0     0     0     0     0     0     0     0

leiden             10    11    12    13
doublets_manual
no                  0  2352  2238     0
yes              3675     0     0  1553
Subsetted cells to: (75466, 2111)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: erythrocyte
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-erythrocyte-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 72246 × 3377
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['11', '3', '10', '4', '6', '13', '5', '3', '7', '9']
leiden               0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               10166  9689  8241     0     0     0     0     0  3922     0
yes                  0     0     0  7959  5588  4505  4282  4014     0  3772

leiden             10    11    12    13   14   15
doublets_manual
no                  0     0  1614     0  611  588
yes              3222  2532     0  1541    0    0
Subsetted cells to: (34831, 3377)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: cd14+cdc2
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-cd14+cdc2-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 9192 × 3561
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['10', '3', '18', '19']
leiden              0     1    2    3    4    5    6    7    8    9   10   11  \
doublets_manual
no               1402  1292  784    0  565  527  518  405  384  351    0  345
yes                 0     0    0  648    0    0    0    0    0    0  345    0

leiden            12   13   14   15   16  17  18  19
doublets_manual
no               322  281  277  259  242  99   0   0
yes                0    0    0    0    0   0  73  73
Subsetted cells to: (8053, 3561)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: cmpcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-cmpcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 1627 × 3943
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['20', '10', '14']
leiden             0    1    2    3    4    5   6   7   8   9  ...  12  13  \
doublets_manual                                                ...
no               211  167  123  121  108  101  98  96  74  68  ...  59  49
yes                0    0    0    0    0    0   0   0   0   0  ...   0   0

leiden           14  15  16  17  18  19  20  21
doublets_manual
no                0  40  29  27  24  22   0  11
yes              47   0   0   0   0   0  21   0

[2 rows x 22 columns]
Subsetted cells to: (1493, 3943)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: corenaivebcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-corenaivebcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 111333 × 1997
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['7', '10', '11']
leiden               0      1      2      3      4      5     6     7     8  \
doublets_manual
no               16027  15998  15943  14316  14129  12578  8460     0  3931
yes                  0      0      0      0      0      0     0  5915     0

leiden              9   10   11
doublets_manual
no               3296    0    0
yes                 0  477  263
Subsetted cells to: (104678, 1997)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: sox4+vd1gdt
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-sox4+vd1gdt-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 214 × 4236
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: []
The list is empty
leiden            0   1   2   3   4   5   6
doublets_manual
no               46  35  34  33  29  20  17
Subsetted cells to: (214, 4236)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: klrf1+effectorvd1gdt
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-klrf1+effectorvd1gdt-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 23473 × 3080
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['6', '5', '7']
leiden              0     1     2     3     4     5    6    7
doublets_manual
no               4878  4634  3697  3663  3544     0    0    0
yes                 0     0     0     0     0  2062  559  436
Subsetted cells to: (20416, 3080)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: isg+naivebcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-isg+naivebcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 6099 × 3377
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['7', '6']
leiden              0    1    2    3    4    5    6    7    8    9   10   11
doublets_manual
no               1134  917  652  564  501  374    0    0  326  325  305  303
yes                 0    0    0    0    0    0  356  342    0    0    0    0
Subsetted cells to: (5401, 3377)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: plasmacell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-plasmacell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 5616 × 4080
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['11', '14', '13', '15', '9']
leiden             0    1    2    3    4    5    6    7    8    9   10   11  \
doublets_manual
no               984  566  563  559  513  404  386  382  308    0  221    0
yes                0    0    0    0    0    0    0    0    0  292    0  147

leiden           12  13  14  15  16
doublets_manual
no               97   0   0   0  38
yes               0  61  55  40   0
Subsetted cells to: (5021, 4080)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: cd4mait
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-cd4mait-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 988 × 3677
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['7', '2']
leiden             0    1   2   3   4   5   6   7   8   9  10  11  12  13
doublets_manual
no               168  101   0  86  79  78  74   0  63  51  49  31  24  24
yes                0    0  96   0   0   0   0  64   0   0   0   0   0   0
Subsetted cells to: (828, 3677)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: corecd14monocyte
Value: data/ndmm-pbmc-celltypes_MS/2025-06-23-ndmm-pbmc-corecd14monocyte-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 492590 × 1898
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['9', '7', '10', '14', '11']
leiden               0      1      2      3      4      5      6      7  \
doublets_manual
no               85026  68775  64068  55455  53188  38857  24137      0
yes                  0      0      0      0      0      0      0  23350

leiden               8      9     10     11    12    13    14
doublets_manual
no               20929      0      0      0  9524  7625     0
yes                  0  14697  13546  10499     0     0  2914
Subsetted cells to: (427584, 1898)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: gzmk+memorycd4treg
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-gzmk+memorycd4treg-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 412 × 3647
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['1']
leiden             0   1   2   3   4   5   6   7
doublets_manual
no               110   0  48  43  40  33  27  24
yes                0  87   0   0   0   0   0   0
Subsetted cells to: (325, 3647)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: isg+cd16monocyte
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-isg+cd16monocyte-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 16810 × 2798
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['8', '15', '4', '6', '11', '14']
leiden              0     1     2     3     4     5    6    7    8    9   10  \
doublets_manual
no               2857  2327  2148  1761     0  1366    0  589    0  543  472
yes                 0     0     0     0  1644     0  762    0  559    0    0

leiden            11   12   13   14   15   16
doublets_manual
no                 0  409  320    0    0  139
yes              449    0    0  263  202    0
Subsetted cells to: (12931, 2798)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: corenaivecd8tcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-corenaivecd8tcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 29141 × 2233
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['13', '12']
leiden              0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               6892  4538  3205  2826  1718  1609  1599  1554  1422  1188
yes                 0     0     0     0     0     0     0     0     0     0

leiden            10   11   12   13
doublets_manual
no               793  662    0    0
yes                0    0  599  536
Subsetted cells to: (28006, 2233)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: sox4+naivecd4tcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-sox4+naivecd4tcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 1387 × 3112
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['6', '5']
leiden             0    1    2    3   4   5   6   7   8   9  10  11  12  13
doublets_manual
no               309  248  220  203  73   0   0  40  37  31  31  28  28  20
yes                0    0    0    0   0  70  49   0   0   0   0   0   0   0
Subsetted cells to: (1268, 3112)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: naivevd1gdt
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-naivevd1gdt-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 536 × 3570
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: []
The list is empty
leiden             0    1   2   3   4   5   6   7   8
doublets_manual
no               134  119  80  50  36  35  30  28  24
Subsetted cells to: (536, 3570)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: isg+mait
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-isg+mait-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 412 × 3321
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['7']
leiden             0   1   2   3   4   5   6   7   8
doublets_manual
no               118  88  36  36  32  31  28   0  20
yes                0   0   0   0   0   0   0  23   0
Subsetted cells to: (389, 3321)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: klrf1-gzmb+cd27-emcd8tcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-klrf1-gzmb+cd27-emcd8tcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 273376 × 1380
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['3', '9', '10']
leiden               0      1      2      3      4      5      6      7  \
doublets_manual
no               44992  43991  42454      0  25150  22378  20575  19950
yes                  0      0      0  30051      0      0      0      0

leiden               8     9    10    11
doublets_manual
no               10962     0     0  1851
yes                  0  8989  2033     0
Subsetted cells to: (232303, 1380)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: cd27+effectorbcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-cd27+effectorbcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 2281 × 3563
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['8', '13']
leiden             0    1    2    3    4    5    6    7    8    9  10  11  12  \
doublets_manual
no               258  237  220  212  181  164  148  135    0  132  98  93  58
yes                0    0    0    0    0    0    0    0  134    0   0   0   0

leiden           13  14  15  16  17  18
doublets_manual
no                0  42  38  32  29  27
yes              43   0   0   0   0   0
Subsetted cells to: (2104, 3563)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: cmcd4tcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-cmcd4tcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 175157 × 1694
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['11']
leiden               0      1      2      3      4      5      6      7  \
doublets_manual
no               26086  24743  20292  19833  16979  16480  13908  12866
yes                  0      0      0      0      0      0      0      0

leiden               8     9    10    11
doublets_manual
no               10134  8325  3457     0
yes                  0     0     0  2054
Subsetted cells to: (173103, 1694)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: hla-drhicdc2
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-hla-drhicdc2-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 10049 × 3180
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['18', '6', '13']
leiden              0     1     2    3    4    5    6    7    8    9   10  \
doublets_manual
no               1340  1277  1131  841  823  728    0  548  405  358  323
yes                 0     0     0    0    0    0  587    0    0    0    0

leiden            11   12   13   14   15   16   17  18
doublets_manual
no               298  270    0  237  216  207  116   0
yes                0    0  266    0    0    0    0  78
Subsetted cells to: (9118, 3180)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: klrb1+memorycd4treg
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-klrb1+memorycd4treg-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 4639 × 3211
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['6', '15']
leiden             0    1    2    3    4    5    6    7    8    9   10   11  \
doublets_manual
no               853  638  483  442  342  274    0  202  188  188  182  182
yes                0    0    0    0    0    0  243    0    0    0    0    0

leiden            12  13  14  15  16
doublets_manual
no               138  93  85   0  41
yes                0   0   0  65   0
Subsetted cells to: (4331, 3211)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: klrb1+memorycd8treg
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-klrb1+memorycd8treg-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 2012 × 3740
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['1', '13', '17']
leiden             0    1    2    3    4    5    6    7    8   9  10  11  12  \
doublets_manual
no               374    0  180  168  162  144  142  134  108  68  59  59  59
yes                0  186    0    0    0    0    0    0    0   0   0   0   0

leiden           13  14  15  16  17
doublets_manual
no                0  46  31  23   0
yes              51   0   0   0  18
Subsetted cells to: (1757, 3740)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: activatedmemorybcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-activatedmemorybcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 952 × 3914
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['6', '4', '5']
leiden             0    1    2   3   4   5   6   7   8   9
doublets_manual
no               315  140  103  84   0   0   0  48  44  27
yes                0    0    0   0  77  58  56   0   0   0
Subsetted cells to: (761, 3914)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: intermediatemonocyte
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-intermediatemonocyte-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 18375 × 2807
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['6', '15']
leiden              0     1     2     3     4     5     6    7    8    9   10  \
doublets_manual
no               2803  2700  1925  1796  1759  1302     0  868  837  829  765
yes                 0     0     0     0     0     0  1223    0    0    0    0

leiden            11   12   13   14   15
doublets_manual
no               738  344  219  149    0
yes                0    0    0    0  118
Subsetted cells to: (17034, 2807)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: proliferatingnkcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-proliferatingnkcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 7088 × 4111
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['6', '16', '17', '9']
leiden             0    1    2    3    4    5    6    7    8    9   10   11  \
doublets_manual
no               881  856  850  764  645  628    0  419  232    0  221  217
yes                0    0    0    0    0    0  421    0    0  227    0    0

leiden            12   13   14  15  16  17
doublets_manual
no               212  177  172  59   0   0
yes                0    0    0   0  56  51
Subsetted cells to: (6333, 4111)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: isg+memorycd4tcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-isg+memorycd4tcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 9687 × 2904
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['12', '14']
leiden              0     1    2    3    4    5    6    7    8    9   10   11  \
doublets_manual
no               1706  1012  762  723  685  663  632  607  588  485  429  429
yes                 0     0    0    0    0    0    0    0    0    0    0    0

leiden            12   13   14   15
doublets_manual
no                 0  253    0  189
yes              283    0  241    0
Subsetted cells to: (9163, 2904)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: corecd16monocyte
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-corecd16monocyte-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 59084 × 2351
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['11', '13', '8']
leiden              0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               8419  8198  7105  6857  6467  4072  3772  3708     0  2551
yes                 0     0     0     0     0     0     0     0  2773     0

leiden             10    11   12   13
doublets_manual
no               2125     0  570    0
yes                 0  1999    0  468
Subsetted cells to: (53844, 2351)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: isg+naivecd4tcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-isg+naivecd4tcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 9024 × 2492
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['13', '14', '10', '11']
leiden              0     1     2    3    4    5    6    7    8    9   10  \
doublets_manual
no               2102  1318  1149  802  666  570  452  418  387  378    0
yes                 0     0     0    0    0    0    0    0    0    0  302

leiden            11   12   13  14
doublets_manual
no                 0  125    0   0
yes              173    0  108  74
Subsetted cells to: (8367, 2492)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: earlymemorybcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-earlymemorybcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 892 × 4195
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['5', '4']
leiden             0    1    2   3   4   5   6   7   8   9  10  11  12
doublets_manual
no               142  127  114  80   0   0  77  56  41  29  26  24  19
yes                0    0    0   0  79  78   0   0   0   0   0   0   0
Subsetted cells to: (735, 4195)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: memorycd8treg
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-memorycd8treg-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 549 × 3853
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['3', '4']
leiden            0   1   2   3   4   5   6   7   8   9
doublets_manual
no               98  92  89   0   0  40  39  35  27  21
yes               0   0   0  60  48   0   0   0   0   0
Subsetted cells to: (441, 3853)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: gzmk-cd27+emcd8tcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-gzmk-cd27+emcd8tcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 1021 × 4007
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['3', '4']
leiden             0    1    2   3   4   5   6   7   8   9  10  11  12  13
doublets_manual
no               302  179  169   0   0  44  29  28  26  21  19  18  15  15
yes                0    0    0  89  67   0   0   0   0   0   0   0   0   0
Subsetted cells to: (865, 4007)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: cd95memorybcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-cd95memorybcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 1715 × 3704
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['11', '10', '14']
leiden             0    1    2    3    4    5   6   7   8   9  10  11  12  13  \
doublets_manual
no               223  188  182  136  134  112  95  93  87  82   0   0  71  46
yes                0    0    0    0    0    0   0   0   0   0  79  74   0   0

leiden           14  15  16
doublets_manual
no                0  41  27
yes              45   0   0
Subsetted cells to: (1517, 3704)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: cdc1
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-cdc1-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 1959 × 4003
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['12', '15', '3', '10', '13']
leiden             0    1    2    3    4    5    6    7    8   9  10  11  12  \
doublets_manual
no               299  284  183    0  175  148  111  108  108  87   0  72   0
yes                0    0    0  177    0    0    0    0    0   0  75   0  42

leiden           13  14  15
doublets_manual
no                0  25   0
yes              40   0  25
Subsetted cells to: (1600, 4003)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: cmcd8tcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-cmcd8tcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 24222 × 2683
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['11', '13']
leiden              0     1     2     3     4     5     6     7     8    9  \
doublets_manual
no               3685  3215  2621  2433  2246  1984  1891  1740  1110  996
yes                 0     0     0     0     0     0     0     0     0    0

leiden            10   11   12   13
doublets_manual
no               809    0  404    0
yes                0  720    0  368
Subsetted cells to: (23134, 2683)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: klrf1+gzmb+cd27-emcd8tcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-klrf1+gzmb+cd27-emcd8tcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 63523 × 2113
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['10', '7', '9']
leiden               0     1     2     3     4     5     6     7     8    9  \
doublets_manual
no               12345  9667  9364  9037  7853  7599  3326     0  1614    0
yes                  0     0     0     0     0     0     0  1624     0  689

leiden            10
doublets_manual
no                 0
yes              405
Subsetted cells to: (60805, 2113)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: type2polarizedmemorybcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-type2polarizedmemorybcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 679 × 3746
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['6']
leiden             0    1   2   3   4   5   6   7   8
doublets_manual
no               135  127  77  73  68  67   0  39  39
yes                0    0   0   0   0   0  54   0   0
Subsetted cells to: (625, 3746)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: cd8aa
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-cd8aa-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 496 × 3417
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['6']
leiden            0   1   2   3   4   5   6   7   8   9  10
doublets_manual
no               83  77  64  62  46  33   0  28  27  27  19
yes               0   0   0   0   0   0  30   0   0   0   0
Subsetted cells to: (466, 3417)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: asdc
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-asdc-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 619 × 3917
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['5', '13']
leiden            0   1   2   3   4   5   6   7   8   9  10  11  12  13
doublets_manual
no               85  74  68  59  47   0  41  38  36  32  31  27  27   0
yes               0   0   0   0   0  41   0   0   0   0   0   0   0  13
Subsetted cells to: (565, 3917)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: naivecd4treg
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-naivecd4treg-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 15268 × 2704
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['8', '10']
leiden              0     1     2     3     4     5    6    7    8    9   10  \
doublets_manual
no               2446  2388  2139  1690  1196  1035  910  727    0  573    0
yes                 0     0     0     0     0     0    0    0  591    0  400

leiden            11   12   13   14   15
doublets_manual
no               366  302  186  179  140
yes                0    0    0    0    0
Subsetted cells to: (14277, 2704)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: cd27-effectorbcell
Value: data/ndmm-pbmc-celltypes_MS/2025-06-22-ndmm-pbmc-cd27-effectorbcell-celltype-harmony-processed.h5ad
AnnData object with n_obs × n_vars = 2912 × 3942
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id', 'aifi_l1', 'aifi_l2', 'aifi_l3', 'predicted_doublet', 'doublet_score', 'sample.sampleKitGuid', 'sample.visitDetails', 'sample.visitName', 'sample.drawDate', 'sample.daysSinceFirstVisit', 'sample.diseaseStatesRecordedAtVisit', 'subject.biologicalSex', 'subject.birthYear', 'subject.ethnicity', 'subject.partnerCode', 'subject.race', 'subject.subjectGuid', 'cohort.cohortGuid', 'manual.time_stamp', 'manual.tissue', 'manual.disease_condition', 'manual.response', 'manual.response_type', 'manual.extracted_name', 'manual.file_paths', 'manual.batch_id', 'manual.cmv.ab_screen_index_value', 'manual.cmv.ab_screen_result', 'manual.cmv.ab_visit', 'manual.igg.iga', 'manual.igg.igg', 'manual.igg.igm', 'manual.igg.immunofixation', 'manual.igg.k_flc', 'manual.igg.kl_flc_ratio', 'manual.igg.l_flc', 'manual.igg.mono_1_id', 'manual.igg.mono_1_quant', 'manual.lip.cholesterol_hdl_ratio', 'manual.lip.cholesterol_hdl', 'manual.lip.cholesterol_ldl', 'manual.lip.cholesterol_non_hdl', 'manual.lip.cholesterol_total', 'manual.lip.triglycerides', 'manual.RISS.stage', 'manual.cyto.17p_loss', 'manual.cyto.1q_gain', 'manual.cyto.1p_loss', 'manual.cyto.high_risk', 'manual.cyto.karyotype', 'manual.cyto.t11_14', 'manual.cyto.t14_16', 'manual.cyto.t14_20', 'manual.cyto.t4_14', 'manual.cyto.karyotype.1', 'tidy.aifi_l2', 'tidy.aifi_l1', 'tidy.aifi_l3', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'leiden'
    var: 'mito', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'mt', 'ribo', 'hb', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 't-test', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_pca_temp', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['11', '13', '15']
leiden             0    1    2    3    4    5    6    7    8    9   10   11  \
doublets_manual
no               401  315  295  278  257  227  211  180  144  139  133    0
yes                0    0    0    0    0    0    0    0    0    0    0  124

leiden           12  13  14  15
doublets_manual
no               88   0  25   0
yes               0  76   0  19
Subsetted cells to: (2693, 3942)
Saving processed data

/home/workspace/environment/ndmm-scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

In [ ]:
print(f"Exported {len(out_files)} cleaned h5ad files")

['data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_gzmb+vd2gdt_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_transitionalbcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_gzmk-cd56dimnkcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_adaptivenkcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_isg+cd56dimnkcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_gzmk+cd27+emcd8tcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_clpcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_baeomapcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_il1b+cd14monocyte_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_cd8mait_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_c1q+cd16monocyte_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_proliferatingtcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_corememorybcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_isg+memorycd8tcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_isg+cdc2_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_dntcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_isg+cd14monocyte_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_isg+naivecd8tcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_cd56brightnkcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_memorycd4treg_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_klrf1-gzmb+cd27-memorycd4tcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_pdc_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_ilc_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_platelet_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_corenaivecd4tcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_klrf1-effectorvd1gdt_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_gzmk+cd56dimnkcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_gzmk+vd2gdt_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_sox4+naivecd8tcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_gzmb-cd27+emcd4tcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_gzmb-cd27-emcd4tcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_erythrocyte_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_cd14+cdc2_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_cmpcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_corenaivebcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_sox4+vd1gdt_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_klrf1+effectorvd1gdt_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_isg+naivebcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_plasmacell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_cd4mait_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_corecd14monocyte_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_gzmk+memorycd4treg_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_isg+cd16monocyte_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_corenaivecd8tcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_sox4+naivecd4tcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_naivevd1gdt_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_isg+mait_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_klrf1-gzmb+cd27-emcd8tcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_cd27+effectorbcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_cmcd4tcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_hla-drhicdc2_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_klrb1+memorycd4treg_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_klrb1+memorycd8treg_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_activatedmemorybcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_intermediatemonocyte_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_proliferatingnkcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_isg+memorycd4tcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_corecd16monocyte_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_isg+naivecd4tcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_earlymemorybcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_memorycd8treg_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_gzmk-cd27+emcd8tcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_cd95memorybcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_cdc1_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_cmcd8tcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_klrf1+gzmb+cd27-emcd8tcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_type2polarizedmemorybcell_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_cd8aa_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_asdc_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_naivecd4treg_2025-06-27.h5ad',
 'data/ndmm-pbmc-celltypes_deepcleaned_objs/ndmm_deepcleaned_cd27-effectorbcell_2025-06-27.h5ad']

## 4 Export Combined Doublet Metadata

In [ ]:
# Concatenate all per-cell-type metadata into a single DataFrame
doublet_meta_comb = pd.concat(meta_list)
print(f"Combined metadata: {doublet_meta_comb.shape[0]:,} cells × {doublet_meta_comb.shape[1]} columns")

In [ ]:
# Doublet removal summary
print(f"Unique L3 cell types: {doublet_meta_comb['tidy.aifi_l3'].nunique()}")
print(doublet_meta_comb['doublets_manual'].value_counts())

72

In [ ]:
# Compute overall removal statistics
n_total = doublet_meta_comb.shape[0]
n_singlets = (doublet_meta_comb['doublets_manual'] == 'no').sum()
n_removed = n_total - n_singlets
pct_removed = (n_removed / n_total) * 100
print(f"Cells removed: {n_removed:,} / {n_total:,} ({pct_removed:.1f}%)")
print(f"Cells retained: {n_singlets:,}")

12.451108302368874

In [ ]:
# Cell counts per L3 cell type in final combined metadata
doublet_meta_comb['tidy.aifi_l3'].value_counts()

tidy.aifi_l3
Core CD14 monocyte                      408667
Core naive CD4 T cell                   341020
KLRF1- GZMB+ CD27- EM CD8 T cell        273376
GZMK+ CD27+ EM CD8 T cell               264574
GZMK- CD56dim NK cell                   180135
CM CD4 T cell                           175157
Core naive B cell                       111333
Other_DC                                 83923
GZMB- CD27- EM CD4 T cell                80694
ISG+ CD14 monocyte                       79831
Erythrocyte                              72246
GZMB- CD27+ EM CD4 T cell                71344
IL1B+ CD14 monocyte                      67464
KLRF1+ GZMB+ CD27- EM CD8 T cell         63523
Memory CD4 Treg                          60594
Adaptive NK cell                         60378
Core CD16 monocyte                       59084
KLRF1- GZMB+ CD27- memory CD4 T cell     51265
CD56bright NK cell                       33378
GZMK+ CD56dim NK cell                    33226
Transitional B cell                      30546
Core naive CD8 T cell                    29141
Platelet                                 26497
CM CD8 T cell                            24222
KLRF1+ effector Vd1 gdT                  23473
Intermediate monocyte                    18375
ISG+ CD16 monocyte                       16810
Naive CD4 Treg                           15268
Core memory B cell                       15179
CD8 MAIT                                 15097
Proliferating T cell                     14486
C1Q+ CD16 monocyte                       11829
ISG+ CD56dim NK cell                     10820
HLA-DRhi cDC2                            10049
ISG+ memory CD4 T cell                    9687
GZMB+ Vd2 gdT                             9351
CD14+ cDC2                                9192
ISG+ naive CD4 T cell                     9024
pDC                                       7638
Proliferating NK cell                     7088
DN T cell                                 6893
ISG+ naive B cell                         6099
Plasma cell                               5616
GZMK+ Vd2 gdT                             5103
KLRB1+ memory CD4 Treg                    4639
KLRF1- effector Vd1 gdT                   3733
CD27- effector B cell                     2912
CD27+ effector B cell                     2281
ISG+ cDC2                                 2119
ISG+ memory CD8 T cell                    2105
KLRB1+ memory CD8 Treg                    2012
cDC1                                      1959
CD95 memory B cell                        1715
CMP cell                                  1627
SOX4+ naive CD4 T cell                    1387
GZMK- CD27+ EM CD8 T cell                 1021
CD4 MAIT                                   988
Activated memory B cell                    952
Early memory B cell                        892
Type 2 polarized memory B cell             679
ASDC                                       619
ISG+ naive CD8 T cell                      552
Memory CD8 Treg                            549
Naive Vd1 gdT                              536
CLP cell                                   502
CD8aa                                      496
ISG+ MAIT                                  412
GZMK+ memory CD4 Treg                      412
ILC                                        309
SOX4+ naive CD8 T cell                     287
SOX4+ Vd1 gdT                              214
BaEoMaP cell                               170
Name: count, dtype: int64

In [ ]:
# Export combined metadata as CSV and pickle for downstream notebooks
doublet_meta_comb.to_csv("../../../data/rna/ndmm-pbmc-193samples-doublet-metadata-all-types.csv")
doublet_meta_comb.to_pickle("../../../data/rna/ndmm-pbmc-193samples-doublet-metadata-all-types.pkl")
print(f"Exported combined metadata: {doublet_meta_comb.shape}")

In [191]:
doublet_meta_comb.shape

(2944774, 102)